### ISSUE TITLE
Unhandleable exception "Could not load key from ... Error: ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by Kesantielu** [ahwayakchih/crx3#10]
If the key file is missing, an exception is thrown to the console, which cannot be handled through the Promise catch.

**Comment by ahwayakchih** [comment]
@Kesantielu yeah, but it's just an information, right? CRX3 should still build project fine.

**Comment by Kesantielu** [comment]
Yes, but it would be better if the info was displayed rather than an exception.

**Comment by ahwayakchih** [comment]
@Kesantielu, is this issue resolved with latest changes merged (see #12 and #13)?
