### ISSUE TITLE
is there a way to extract the crx3 files

### ISSUE THREAD

**Issue by saostad** [ahwayakchih/crx3#11]
I need to extract the Chrome extension files for an electron app. is there a way to extract the crx3 files?

**Comment by ahwayakchih** [comment]
It's not what this module is about (it does not read CRX3 files, nor can it extract ZIP files).
But it's possible write module that would extract ZIP archive from CRX3 file, and then extract the files.

**Comment by saostad** [comment]
That would be a practical module. Could you please explain how I can do that?

**Comment by ahwayakchih** [comment]
Check https://github.com/ahwayakchih/crx3/blob/7384e83d288698fdd4e45add6c0acc4eb05754fd/lib/crx3.proto#L11-L18
CRX3 file starts with a CRX header, which is then followed by a ZIP archive data. Read header to get its size, skip the size of bytes, read ZIP archive.
