### ISSUE TITLE
Different code on GitHub and npm

### ISSUE THREAD

**Issue by shushpan** [ahwayakchih/crx3#3]
, the package is awesome, really useful for  case, thx! 
I've installed this package through npm and faced that it doesn't have changes which make `update.xml` file. This configuration doesn't work:
```
crx3(["build/manifest.json"], {
    keyPath: 'build.pem',
    crxPath: 'nc.crx',
    zipPath: 'nc.zip',
    xmlPath: 'nc.xml',
    crxURL: "https://example.com/update.xml",
    appVersion: "2.0.5"
}).then(() => console.log('done')).catch(console.error)
```

So, I dived under the hood of this package (which download and placed in `node_modules`) and didn't see any part of code which can make xml file but it exists here on Github.

**Comment by shushpan** [comment]
Also, everything works if install package from Github.

**Comment by ahwayakchih** [comment]
@shushpan yes, you're right. I did not prepare new release yet, as i got stuck on improving automated tests and had no free time to finish it.
"Good news" is that i just finished work project and have no other in the pipeline for now, so i will have time to update this one ;).
I'll try to update it over the weekend.

Thanks for the info :).

**Comment by shushpan** [comment]
@ahwayakchih Great, thanks :)

**Comment by ahwayakchih** [comment]
@shushpan i'm sorry it took me so long, but it's finally done and released on npm :).

**Comment by shushpan** [comment]
@ahwayakchih Great, thx!
